name: MCCreativeLabExtension
version: '1.0'
main: de.verdox.mccreativelab.MCCreativeLabExtension
description: MCCreativeLab Plugin Extension
api-version: '1.20'
load: STARTUP

commands:
  fakeblock:
    description: "Fake Block command"